#!/bin/bash

set -e
set -u
set -o pipefail

DISTS=${DISTS:-"trixie
sid
latest
"}

BASENAME=valksor/minideb
DOCKER_REGISTRY=${DOCKER_REGISTRY:-"ghcr.io"}
PLATFORMS=${PLATFORMS:-"amd64 arm64"}
read -r -a ARCHS <<<"$PLATFORMS"

if [ -n "${DOCKER_PASSWORD:-}" ]; then
    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" \
        --password-stdin "${DOCKER_REGISTRY}"
fi

push_manifest() {
    local image="$1"
    shift
    local archs=("$@")
    local arch_images=()
    for arch in "${archs[@]}"; do
        arch_images+=("${image}-${arch}")
    done
    docker buildx imagetools create -t "$image" "${arch_images[@]}"
}

for tag in $DISTS; do
    push_manifest "${DOCKER_REGISTRY}/${BASENAME}:${tag}" "${ARCHS[@]}"
done
